### PR TITLE
More logo file formats

### PR DESCRIPTION
**Pull request by TheBrenny**
Added a PNG and SVG file format, for those who are unable to use the PSD
format.

Not too sure on how it will look once live, though. Should be fine.

### CODE REVIEW

**Comment by daviddarnes** [comment]
Erm, this doesn't look right…
screen shot 2016-08-07 at 12 01 44

**Comment by TheBrenny** [comment]
Oh. That's quite... Uhh. Interesting. :joy_cat: Lemme fix that.

**Comment by daviddarnes** [comment]
@TheBrenny I do already have all these file formats for Anchor Themes, want me to use them?

**Comment by daviddarnes** [comment]
@TheBrenny 😂 haha, that's not quite how SVGs work I'm afraid

**Pull request closed without merging**
